# Generated by Django 2.0 on 2017-12-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animals',
            name='picture',
        ),
        migrations.AddField(
            model_name='animals',
            name='url',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
